RADTik v4 - SMTP Configuration Test Email

This is a test email sent from RADTik v4 Email Settings.

If you received this email, your SMTP configuration is working correctly!

Configuration Details:
- Sent at: {{ now()->format('Y-m-d H:i:s') }}
- System: RADTik v4
- Test Type: SMTP Configuration

This email was automatically generated by the Email Settings page in the Super Admin panel.

Thank you for using RADTik v4!